spring.application.name=berthau
spring.datasource.url=jdbc:mysql://localhost:3306/berthau_api
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api